name: Lint
# Lint runs golangci-lint over the entire Juno repository.
# This workflow is run on every pull request and push to master.
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - cosmos/*

jobs:
  GolangCI:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout 
      - uses: actions/checkout@v3
      - name: Compute Diff 
      - uses: technote-space/get-diff-action@v4
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.28
          args: --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: "env.GIT_DIFF != ''"
